accounts/urls.py
from django.conf.urls import url
from . import views


app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.LeaderboardsListView.as_view(), name='leaderboards'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^player_creation$', views.player_creation, name='player_creation')
]

clicker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.homepage, name='home'),
    url(r'^index/$', views.main_menu, name='main_menu'),
    url(r'^about/$', views.about, name='about'),
    url(r'^game/', include('game.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^accounts/', include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

game/urls.py
from django.conf.urls import url
from . import views

app_name = 'game'

urlpatterns = [
    url(r'^$', views.playscreen, name='playscreen'),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    #url(r'^$', views.ShopItemsList.as_view(), name='itemlist'),
    url(r'^$', views.shop_items_list, name='itemlist'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import ClickButtonSkin, Background, ClickMultiplier

class PlayerInventory(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, default=None, editable=False)
    name = models.ForeignKey(User, default=None)
    total_clicks = models.IntegerField(default=0)
    equipped_button = models.ForeignKey(ClickButtonSkin, default=None)
    equipped_background = models.ForeignKey(Background, default=None)
    equipped_mltplr = models.ForeignKey(ClickMultiplier, default=None)

    class Meta():
        verbose_name = 'Player'
        verbose_name_plural = "Players' stats"

    def __str__(self):
        return self.name.username

game/models.py
from django.db import models

shop/models.py
from django.db import models

class ClickButtonSkin(models.Model):
    btn_name = models.CharField(max_length=30)
    btn_image = models.ImageField()
    btn_price = models.IntegerField(unique=True)

    class Meta():
        verbose_name  = 'click button'
        verbose_name_plural = 'Buttons'

    def __str__(self):
        return self.btn_name

class Background(models.Model):
    bkg_name = models.CharField(max_length=30)
    bkg_image = models.ImageField()
    bkg_price = models.IntegerField(unique=True)

    def __str__(self):
        return self.bkg_name

class ClickMultiplier(models.Model):
    mltplr_name = models.CharField(max_length=10)
    mltplr_value = models.IntegerField(unique=True)
    mltplr_price = models.IntegerField(unique=True)

    def __str__(self):
        return self.mltplr_name

accounts/forms.py
from django.forms import ModelForm
from .models import PlayerInventory

class CreatePlayerInventoryInstanceForm(ModelForm): #name too long?
    class Meta():
        model = PlayerInventory
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.views.generic import ListView
from accounts.models import PlayerInventory
from shop.models import ClickButtonSkin, Background, ClickMultiplier
from .forms import CreatePlayerInventoryInstanceForm


class LeaderboardsListView(ListView):
    model = PlayerInventory
    template_name = 'accounts/leaderboards.html'
    context_object_name = 'list_of_players'

    def get_queryset(self):
        return PlayerInventory.objects.all().order_by('-total_clicks')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_length'] = len(self.get_queryset())
        return context

def signup(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:player_creation')
    else:
        form = UserCreationForm()

    template = 'accounts/signup.html'
    context = {
        'signup_form': form,
    }
    return render(request, template, context)

def player_creation(request):
    if request.method == 'GET':
        create_player_form = CreatePlayerInventoryInstanceForm()
        instance = create_player_form.save(commit=False)
        instance.name = request.user
        print(request.user, '\n\n\n\n')
        instance.total_clicks = 0
        instance.equipped_button_id = ClickButtonSkin.objects.get(btn_name='default').id
        instance.equipped_background_id = Background.objects.get(bkg_name='default_bkg').id
        instance.equipped_mltplr_id = ClickMultiplier.objects.get(mltplr_name='x1').id
        instance.save()

    return redirect('main_menu')


def user_login(request):

    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('main_menu')

    else:
        form = AuthenticationForm()
    template = 'accounts/login.html'
    context = {
        'login_form': form
    }
    return render(request, template, context)

def user_logout(request):

    if request.method == 'POST':
        logout(request)
        return redirect('main_menu')

clicker/views.py
from django.shortcuts import render, redirect

def homepage(request):
    return redirect('main_menu')

def main_menu(request):
    template = 'main_menu.html'

    return render(request, template)

def about(request):
    template = 'about.html'

    return render(request, template)

game/views.py
from django.shortcuts import render
from django.db.models import F
from accounts.models import PlayerInventory

def playscreen(request):

    template = 'game/playscreen.html'

    if request.POST.get('user-id'):
        current_player = PlayerInventory.objects.get(name=request.POST.get('user-id'))
        var = None
        if request.POST.get('add-click'):
            current_player.total_clicks=F('total_clicks') + 1*current_player.equipped_mltplr.mltplr_value
            current_player.save()
            current_player = PlayerInventory.objects.get(name=request.POST.get('user-id'))
        context = {
            'player': current_player,
            'var': var,
        }

    else:
        context = {

        }
    return render(request, template, context)

shop/views.py
from shop.models import ClickButtonSkin, Background, ClickMultiplier
from accounts.models import PlayerInventory
from django.shortcuts import  render

def shop_items_list(request):
    template = 'shop/itemlist.html'
    player = PlayerInventory.objects.get(name=request.user.id)
    button_list = ClickButtonSkin.objects.filter(btn_price__lte=player.total_clicks).order_by('btn_price')
    background_list = Background.objects.filter(bkg_price__lte=player.total_clicks).order_by('bkg_price')
    mltplr_list = ClickMultiplier.objects.filter(mltplr_price__lte=player.total_clicks).order_by('mltplr_value')
    if request.POST.get('apply-button'):
        player.equipped_button = ClickButtonSkin.objects.get(id=request.POST.get('apply-button'))
        player.save()
        player = PlayerInventory.objects.get(name=request.user.id)
    if request.POST.get('apply-background'):
        player.equipped_background = Background.objects.get(id=request.POST.get('apply-background'))
        player.save()
        player = PlayerInventory.objects.get(name=request.user.id)
    if request.POST.get('apply-multiplier'):
        player.equipped_mltplr = ClickMultiplier.objects.get(id=request.POST.get('apply-multiplier'))
        player.save()
        player = PlayerInventory.objects.get(name=request.user.id)
    context = {
        'player': player,
        'button_list': button_list,
        'background_list': background_list,
        'multiplier_list': mltplr_list
    }
    return render(request, template, context)

accounts/templates/accounts/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE HTML>
<html>
    <head>
        <title>Accounts</title>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{% static 'accounts/styles.css' %}">
    </head>
    <body>
        <div id="header">
            <h1><a href="{% url 'home' %}">clicker</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

accounts/templates/accounts/leaderboards.html
{% extends 'accounts/base_layout.html' %}
{% load static from staticfiles %}

{% block content %}
<div id="leaderboards">
    <div>
        <form class="accounts" action="{% url 'main_menu' %}">
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Main Menu</button>
        </form>
        <p><h4>Leaderboards</h4></p>
        <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
            <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric">Player</th>
                <th class="mdl-data-table__cell--non-numeric">Score</th>
            </tr>
            </thead>
            <tbody>
            {% if list_length == 0 %}
            <tr>
                <td>empty</h4></td>
                <td>empty</td>
            </tr>
            {% else %}
            {% for player in list_of_players %}
            <tr>
                <td>{{ player.name }}</td>
                <td>{{ player.total_clicks }}</td>
            </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
        <br>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_layout.html' %}

{% block content %}
    <div id="login">
        <div>
        <dl>
            <dt><h4>Login</h4></dt>
            <dd>
                <form name="login-form" action="{% url 'accounts:login' %}" method="post">
                    {{ login_form }}
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}" />
                    {% endif %}
                    <p><input name="submit-login" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit" value="Log me in!" /></p>
                </form>
            </dd>
        </dl>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/base_layout.html' %}

{% block content %}
    <div id="signup">
        <div>
        <dl>
            <dt><h4>Become a player</h4></dt>
            <dd>
                <form name="signup-form" action="{% url 'accounts:signup' %}" method="post">
                    {{ signup_form }}
                    {% csrf_token %}
                    <input name="submit-signup" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit" value="Signup" />
                </form>
            </dd>
        </dl>
        </div>
    </div>
{% endblock %}

game/templates/game/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE HTML>
<html>
<head>
    <title>The game itself</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'game/styles.css' %}">
</head>
<body>
    <div id="header">
        <h1><a href="{% url 'home' %}">clicker</a></h1>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

game/templates/game/playscreen.html
{% extends 'game/base_layout.html' %}
{% load static %}

{% block content %}
<div id="game">
    <div id="go-to-main-menu">
            <form class="accounts" action="{% url 'main_menu' %}">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Main Menu</button>
            </form>
    </div>
    {% if user.is_authenticated %}
        <div id="playscreen" style="background-image: url({% get_media_prefix %}{{ player.equipped_background.bkg_image }}); background-size: cover;">
            <p>
                <form id="click-button" action="{% url 'game:playscreen' %}" method="post">
                    {% csrf_token %}
                    <input type="image" src="{% get_media_prefix %}{{ player.equipped_button.btn_image }}" value="Click!"/>
                    <input type="hidden" name="add-click" value="{{ var }}"/>
                    <input type="hidden" name="user-id" value="{{ request.user.id }}" />
                </form>
            </p>
            <p>Playing as {{ player.name }}</p>
            <p>Your score is: <b>{{ player.total_clicks }}</b></p>
        </div>
    {% else %}
        <script>
            var total_clicks = 0;

            function add_click() {
                total_clicks++;
                document.querySelector('#clicks').innerHTML = total_clicks;
            }

        </script>
        <p><input type="image" src="{% static 'shop/default.png' %}" id="add-click-unauth" value="Click!" onclick="add_click();" /></p>
        <p>You've clicked <b id="clicks">0</b> times</p>
    {% endif %}
</div>
{% endblock %}

shop/templates/shop/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE HTML>
<html>
<head>
    <title>Bells and whistles</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'shop/styles.css' %}">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</head>
<body>
    <div id="header">
        <h1><a href="{% url 'home' %}">clicker</a></h1>
    </div>
    <div id="shop">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

shop/templates/shop/itemlist.html
{% extends 'shop/base_layout.html' %}
{% load static %}

{% block content %}
<div id="shop">
    <div id="items">
        <div id="go-to-main-menu">
            <form class="accounts" action="{% url 'main_menu' %}">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Main Menu</button>
            </form>
        </div>
        <p><h4>Unlock more items by playing the game</h4></p>
        <p><h4>As {{ player.name }} you've clicked {{ player.total_clicks }} times</h4></p>
        <div id="buttons" class="item-class">
            <p>Available buttons</p><br>
            {% for item in button_list %}
            <div class="demo-card-square mdl-card mdl-shadow--2dp">
                <div class="mdl-card__title mdl-card--expand"
                     style="background: url({% get_media_prefix %}{{ item.btn_image }});
                       background-repeat: no-repeat;
                       background-size: 30%;
                       background-position: 80%">
                    <!-- can't use template tags in css files, moved background style here -->
                    <h2 class="mdl-card__title-text">{{ item.btn_name }}</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    Unlocked for reaching {{ item.btn_price }} points
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <form method="post" action="{% url 'shop:itemlist' %}">
                        {% csrf_token %}
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Apply</button>
                        <input name="apply-button" type="hidden" value="{{ item.id }}">
                    </form>
                    </a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
        <div id="backgrounds" class="item-class">
            <p>Available backgrounds</p><br>
            {% for item in background_list %}
            <div class="demo-card-square mdl-card mdl-shadow--2dp">
                <div class="mdl-card__title mdl-card--expand"
                     style="background: url({% get_media_prefix %}{{ item.bkg_image }});
                       background-repeat: no-repeat;
                       background-size: 100%;">
                    <!-- can't use template tags in css files, moved background style here -->
                <h2 class="mdl-card__title-text">{{ item.bkg_name }}</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    Unlocked for reaching {{ item.bkg_price }} points
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <form method="post" action="{% url 'shop:itemlist' %}">
                        {% csrf_token %}
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Apply</button>
                        <input name="apply-background" type="hidden" value="{{ item.id }}">
                    </form>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
        <div id="multipliers" class="item-class">
            <p>Available multipliers</p><br>
            {% for item in multiplier_list %}
            <div class="demo-card-square mdl-card mdl-shadow--2dp">
                <div id="mltplr-name" class="mdl-card__title mdl-card--expand">
                    <h2 class="mdl-card__title-text">{{ item.mltplr_name }}</h2>
                </div>
                <div class="mdl-card__supporting-text">
                    Unlocked for reaching {{ item.mltplr_price }} points
                </div>
                <div class="mdl-card__actions mdl-card--border">
                    <form method="post" action="{% url 'shop:itemlist' %}">
                        {% csrf_token %}
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Apply</button>
                        <input name="apply-multiplier" type="hidden" value="{{ item.id }}">
                    </form>
                    </a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
    <dl>
        <div id="description">
            <dl>
                <dt>Description</dt>
                <dd>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>
                    Etiam ac condimentum enim. Fusce dictum vestibulum odio, <br>
                    ac ultricies tortor tempus eget. Vestibulum vel tellus ante. <br>
                </dd>
            </dl>
        </div>
        <div id="contact-us">
            <dl>
                <dt>Contact us</dt>
                <dd>
                    <dl>
                        <div class="contact-method">
                            <dt>By phone</dt>
                            <dd>1-800-CLICKER</dd>
                        </div>
                        <div class="contact-method">
                            <dt>By e-mail</dt>
                            <dd>clicker@randommail.com</dd>
                        </div>
                    </dl>
                </dd>
            </dl>
        </div>

    </ul>
{% endblock %}

templates/base_layout.html
{% load static  from staticfiles %}

<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Main menu</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <div id="header">
            <h1><a href="{% url 'home' %}">clicker</a></h1>
        </div>
        <div id="main-menu">
        <nav>
            <ul>
                <li>
                    <form class="accounts" id="go-to-main-menu" action="{% url 'main_menu' %}">
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Main Menu</button>
                    </form>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <form class="accounts" id="logout-button" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Logout</button>
                    </form>
                </li>
                <p>Logged in as <span id="username">{{ request.user.username }}</span></p>
                {% else %}
                <li>
                    <form class="accounts" id="login-button" action="{% url 'accounts:login' %}" method="post">
                        {% csrf_token %}
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Login</button>
                    </form>
                </li>
                <li>
                    <form class="accounts" id="signup-button" action="{% url 'accounts:signup' %}" method="post">
                        {% csrf_token %}
                        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Signup</button>
                    </form>
                </li>
                {% endif %}

            </ul>
        </nav>
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

templates/main_menu.html
{% extends 'base_layout.html' %}

{% block content %}
    <dl>
        <div id="play-the-game" class="menu-option">
            <dt><form action="{% url 'game:playscreen' %}" method="post">
                {% csrf_token %}
                {% if request.user.id is not None %}
                <input type="hidden" name="user-id" value="{{ request.user.id }}" />
                {% endif %}
                <button id="start-playing" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Play the game!</button>
            </form></dt>
            <dd>How to play:
                <ol><li>Click the button to earn points</li>
                    <li>See 1</li></ol></dd>
        </div><br>
        {% if user.is_authenticated %}
        <div id="visit-the-shop" class="menu-option">
            <dt><form action="{% url 'shop:itemlist' %}">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Visit the shop</button>
            </form></dt>
            <dd>Change the look of the click button and its background</dd>
        </div><br>
        <div id="leaderboards" class="menu-option">
            <dt><form action="{% url 'accounts:leaderboards' %}">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">Leaderboards</button>
            </form></dt>
            <dd>See how you're doing compared to others!</dd>
        </div><br>
        {% else %}
        <div class="menu-option">
            <dd> Joining the (currently non-existing) community of clickers<br>
                allows you to:<br>
                <ul>
                    <li>Save your progress</li>
                    <li>Change the look of the game</li>
                    <li>See the leaderboards</li>
                </ul>
            </dd><br>
        </div>
        {% endif %}
        <div id="about" class="menu-option">
            <dt><form action="{% url 'about' %}">
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">About us</button>
            </form></dt>
        </div>
    </dl>
{% endblock %}